name: MarpCLI-GitHub-Actions
on:
  push:
    branches:
      - master
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
          while read line;
          do
            echo $line >> $GITHUB_ENV
          done<./config
      - name: Create output base dir
        run: |
          mkdir ${{env.OUTPUT_DIR_BASE}}
          chmod 777 -R $_
      - name: Export HTML
        run: docker run --rm --init -v "$(pwd):/home/marp/app/"
          -e LANG="ja_JP.UTF-8" -e MARPID="$(id -u):$(id -g)" marpteam/marp-cli
          --input-dir ${{env.INPUT_DIR}}
          --HTML
          --theme ${{env.THEME_CSS}}
          -o ${{env.OUTPUT_DIR_BASE}}/html/
          --allow-local-files
      - name: Export PPTX
        run: docker run --rm --init -v "$(pwd):/home/marp/app/"
          -e LANG="ja_JP.UTF-8" -e MARPID="$(id -u):$(id -g)" marpteam/marp-cli
          --input-dir ${{env.INPUT_DIR}}
          --PPTX
          --theme ${{env.THEME_CSS}}
          -o ${{env.OUTPUT_DIR_BASE}}/pptx/
          --allow-local-files
